### ISSUE TITLE
Laravel Namespace ?

### ISSUE THREAD

**Issue by vluzrmos** [eusonlito/laravel-FormManager#1]
Why you don't create your own namespace, man?

**Comment by stivyw** [comment]
Yeah man, you can create your own namespace.

**Comment by stivyw** [comment]
Eu sou anti-bule.

**Comment by vluzrmos** [comment]
@taylorotwell Dislike that package namespace (on packagist) and that is his trademark.

**Comment by limatheus** [comment]
Good job, just use your own namespace and make it awesome.

**Comment by stivyw** [comment]
Fixe:
`namespace Laravel\FormManager;`
to 
`namespace Eusoulindo\FormManager;`
And make all hapy \o/

**Comment by vluzrmos** [comment]
and change it on composer.json

**Comment by stivyw** [comment]
Good

**Comment by eusonlito** [comment]
Ok! thanks, I will do it today (and also to my others packages) :+1:

**Comment by vluzrmos** [comment]
:+1:

**Comment by eusonlito** [comment]
There are about 16,884 repositories with Laravel in name. I will update namespace to "Eusonlito" but name to "LaravelFormManager" because is an exclusive package to Laravel.
